class Qbit
  attr_reader vector: Matrix

  attr_reader entanglement: Array[Entanglement]

  include VectorHelper

  def initialize: (Numeric zero_prob, Numeric one_prob) -> Qbit

  def vector=: (Array[Numeric] vector) -> untyped

  def measure: () -> Integer

  def zero_probability: () -> Numeric

  def one_probability: () -> Numeric

  def entangled?: () -> bool

  def to_s: () -> (nil | String)
end
