class Qbit
  attr_reader vector: Matrix

  attr_reader entanglement: Array[Entanglement]

  include VectorHelper

  def initialize: (Numeric zero_prob, Numeric one_prob) -> Qbit

  def self.generate: () -> Qbit

  def vector=: (Array[Numeric] vector) -> untyped

  def measure: () -> Integer

  def zero_el: () -> Numeric

  def one_el: () -> Numeric

  def entangled?: () -> bool

  def measured?: () -> bool

  def to_s: () -> (nil | String)

  def zero_string: () -> String

  def one_string: () -> String

  def to_str: () -> (nil | String)
end
