class Qubit
  attr_reader vector: Matrix

  attr_accessor entanglement: bool

  include VectorHelper

  def initialize: (Numeric zero_prob, Numeric one_prob) -> untyped

  def vector=: (Array vector) -> untyped

  def measure: () -> Integer

  def zero_probability: () -> Numeric

  def one_probability: () -> Numeric

  def entangled?: () -> bool

  def to_s: () -> (nil | String)
end
